### ISSUE TITLE
Typo on collection

### ISSUE THREAD

**Issue by ntaphadrian** [NetAppDocs/cloudinsights#1107]
Page: [Configuring an Agent to Collect Data](https://docs.netapp.com/us-en/cloudinsights/task_config_telegraf_agent.html)

When you install the kube-state-metrics server you can enable **colletction** of the following Kubernetes objects: StatefulSet, DaemonSet, Deployment, PV, PVC, ReplicaSet, Service, Namespace, Secret, ConfigMap, Pod Volume, and Ingress.

**Comment by netapp-alavoie** [comment]
Thanks for the catch!  

I have fixed the issue in this and the Kubernetes data collector topic and you should see the fix in the documentation in the next 30 minutes or so.

-Tony
