### ISSUE TITLE
MacOS Uninstall Agent step numbers incorrect.

### ISSUE THREAD

**Issue by seanluce** [NetAppDocs/cloudinsights#1140]
Page: [Configuring an Agent to Collect Data](https://docs.netapp.com/us-en/cloudinsights/task_config_telegraf_agent.html)

"1."
"1."
"2."

should be...

1.
2.
3.

**Comment by netapp-alavoie** [comment]
Thanks for the catch!  Looks like the automatic step numbering was thrown off by an extra blank line in the source doc.  This has been fixed and the update will be live shortly.
