### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/cloudinsights#1185]
`objects assCloud Insightsated` has space for improvement

Page: [Performance Troubleshooting](https://docs.netapp.com/us-en/cloudinsights/concept_faq.html)

**Comment by netapp-alavoie** [comment]
Thanks for the comment.  Looks like a copy/past error in some background docs.  I will go through and fix them.

**Comment by netapp-alavoie** [comment]
I believe these are fixed.  Please re-open or open a new ticket if other typos are noticed.
