### ISSUE TITLE
Default annotation rules in Cloud Insights

### ISSUE THREAD

**Issue by ajewell59** [NetAppDocs/cloudinsights#1226]
Page: [Using annotations](https://docs.netapp.com/us-en/cloudinsights/task_create_annotation.html)

I am wondering if this section is in error?  I have looked at a customer tenant and the cloud central sandbox and do not find the default rules as explained in the online documention.  Neither do i find a way to determine if a rule is default or customer defined.
Please advise and/or update documenation.

**Comment by netapp-alavoie** [comment]
Thank you for your comment.

This section was in error. Cloud Insights does not include any default annotation rules; the relevant section has been removed from the documentation.

Thank you for bringing this to our attention.

-Tony Lavoie
Cloud Insights Information Engineering
