### ISSUE TITLE
Mention of OS-level configuration.

### ISSUE THREAD

**Issue by mkniep** [NetAppDocs/cloudinsights#1367]
Page: [Cloud Secure Agent Installation](https://docs.netapp.com/us-en/cloudinsights/task_cs_add_agent.html)

I've encountered a few instances where users who configure the open ports mentioned on this page in the 'Network Requirements' at the network level (i.e., in the Azure VM Networking config), but it was not clear to them that this must be done locally on the OS. Could we have the step changed to clarify that, or maybe include this somewhere in the requirements/install steps?

**Comment by netapp-alavoie** [comment]
Would this be enough in this case, or should we say more? (emphasis is mine and will not appear in the final publication)

Network Configuration
**Run** the following commands **on the local system** to open ports **that will** be used by Cloud Secure.

Steps
...

**Comment by netapp-alavoie** [comment]
I made the above change to the CS Agent Installation page.
