### ISSUE TITLE
Data Source enhancements don't seem to make it into the What's New section

### ISSUE THREAD

**Issue by mkniep** [NetAppDocs/cloudinsights#1368]
Page: [What’s New with Cloud Insights](https://docs.netapp.com/us-en/cloudinsights/concept_whats_new.html)

As title suggest, not many are in there - but I know a lot of enhancements have been done (i.e., fpolicy monitoring for ONTAP, HCP data source enhancements, etc.) It would be really helpful to include that kind of thing just like what was historically done with the OCI Release Notes.

**Comment by netapp-alavoie** [comment]
Cloud Insights What's New now mentions the significant Data Collector changes.
