### ISSUE TITLE
Add notice about required rights

### ISSUE THREAD

**Issue by pascaldewild** [NetAppDocs/cloudinsights#1370]
Page: [Importing from the Dashboard Gallery](https://docs.netapp.com/us-en/cloudinsights/concept_import_from_dashboard_gallery.html)

Is it possible to add a notice to this page? I think you need admin rights to import dashboards? The other option would be to NOT require admin rights to import dashboards, which makes even more sense ;)

**Comment by netapp-alavoie** [comment]
Hi and thanks for this comment.  I have verified that only Admin users can import dashboards and am making the following addition to the documentation page (emphasis is mine, will not display on published page):

"Administrator and Account Owner can perform all functions, as well as create, modify and delete policies, ***import dashboards,*** and manage all users and data collectors."
