### ISSUE TITLE
Network requirement

### ISSUE THREAD

**Issue by naopong** [NetAppDocs/cloudinsights#1417]
Page: [Acquisition Unit Requirements](https://docs.netapp.com/us-en/cloudinsights/concept_acquisition_unit_requirements.html)
Network
Please add the following description for network settings.
- Allow outbound traffic.
- No inbound traffic from Cloud Insights.

**Comment by netapp-alavoie** [comment]
Details about traffic can be found in the https://docs.netapp.com/us-en/cloudinsights/security_overview.html#network-security page.
