### ISSUE TITLE
Regarding Sizing: number of ONTAPs

### ISSUE THREAD

**Issue by naopong** [NetAppDocs/cloudinsights#1418]
Page: [Acquisition Unit Requirements](https://docs.netapp.com/us-en/cloudinsights/concept_acquisition_unit_requirements.html)
Please specify that "10 large ONTAP" means more than 10 nodes.
It's not 10 clusters, is it?

**Comment by netapp-alavoie** [comment]
Docs will correct this to "10 large (>2 node) ONTAP clusters"
