### ISSUE TITLE
Regarding Sizing: Disk Increases

### ISSUE THREAD

**Issue by naopong** [NetAppDocs/cloudinsights#1419]
Page: [Acquisition Unit Requirements](https://docs.netapp.com/us-en/cloudinsights/concept_acquisition_unit_requirements.html)
Regarding the increase of disk size, in the case of Linux, please specify the amount of increase for each directory.

**Comment by netapp-alavoie** [comment]
The docs will clarify that all the ancillary space should  be added to the log location.
