### ISSUE TITLE
I would like the description to be a little easier to understand, whether it can be registered in SVM units or it can only be registered in Cluster units.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/cloudinsights#1441]
Page: [NetApp ONTAP Data Management Software Data Collector](https://docs.netapp.com/us-en/cloudinsights/task_dc_na_cdot.html)

>Requirements
> You must have access to an Administrator account configured for read-only API calls.

Does that "Administrator" mean cluster admin and/or svm admin?
I understand that cluster admin (= default vserver?) is the best, but is it possible to set it with SVM admin as well?

> Account details include username and password.

Can I use the SVM admin username?

> Account permissions:
>  Read only role name to ontapi application to the default Vserver

Does the default Vserver mean AdminSVM?

>Configuration
>NetApp Management IP | IP address or fully-qualified domain name of the NetApp cluster
> User Name | User name for NetApp cluster
> Password | Password for NetApp cluster

Is the "for NetApp cluster" mean cluster user privilege?

>A Note About Permissions
##snip##
>To create a local account for Cloud Insights at the cluster level, ##snip#

Can I create and use a local account for Cloud Insights at the svm level?

Thanks,
Kan Itani (kan.itani@netapp.com)

**Comment by netapp-alavoie** [comment]
I am looking into this now and will update the docs as necessary once I have answers to these questions.

**Comment by netapp-alavoie** [comment]
Closing based on age and subsequent page updates.  Please enter a new comment if any open questions.
