### ISSUE TITLE
Still docker-ce configuration is required to configure Cloud Secure for CVO?

### ISSUE THREAD

**Issue by toshiki-mukaeda** [NetAppDocs/cloudinsights#1447]
Page: [Configuring the Cloud Volumes ONTAP Data Collector](https://docs.netapp.com/us-en/cloudinsights/task_config_cs_incloud.html)

Still docker-ce configuration is required to configure Cloud Secure for CVO?

There is no description about docker-ce is required in agent requirements page.
https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html

There is another agent installation steps before this page.
https://docs.netapp.com/us-en/cloudinsights/task_cs_add_agent.html#before-you-begin

It seems agent installation steps are duplicated for CVO.  Please make it clear the cloud secure deployment procedure for CVO.

**Comment by netapp-alavoie** [comment]
Docker references have been removed from these pages.  Docker is no longer a requirement for CS Agent installation.
