### ISSUE TITLE
I want to know if the customer's personal information collected by Cloud Secure cannot be referenced by NetApp.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/cloudinsights#1497]
Page: [Cloud Insights Security](https://docs.netapp.com/us-en/cloudinsights/security_overview.html)

I understand that customer data is encrypted and stored. But I want to make sure that the Cloud Insights operations team can't decrypt and reference that data.

>Collection and protection of customer data
>All customer data is encrypted in transit across public networks and encrypted at rest. Cloud Insights utilizes encryption at various points in the system to protect customer data using technologies that includes Transport Layer Security (TLS) and the industry-standard AES-256 algorithm.

**Comment by netapp-alavoie** [comment]
Hi Kan,

I understand that you and Kai have discussed this, and he can provide further information if you need it. There are no plans to update the documentation at this time.

**Comment by kanitani** [comment]
Please add these words in the document.
"The Cloud Insights operations team can't decrypt and reference that data."
