### ISSUE TITLE
Request to fix the document

### ISSUE THREAD

**Issue by m0ttai** [NetAppDocs/cloudinsights#1500]
Hi Teams, 

I found two errors in the document.
Could you correct sentences?

1. Create a read-only role using the following two commands.
In this sentence, it is written that "two commands".
But in reality three commands are written.

2. The resulting role and user login will look something like this:
This resulting role shows that two directories are allowed.
But in the previous step allowed three directories.
Do you need "cluster application-record create"?

Regards, 

Page: [NetApp ONTAP Data Management Software Data Collector](https://docs.netapp.com/us-en/cloudinsights/task_dc_na_cdot.html#a-note-about-permissions)

**Comment by netapp-alavoie** [comment]
Good morning!  
I have corrected the first issue in the docs, and am looking into the second.

**Comment by netapp-alavoie** [comment]
We qualify the results with the statement "The resulting role and user login will look something like the following. Your actual output may vary."
