### ISSUE TITLE
What are the firewall requirements for Australia?

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/cloudinsights#1516]
Page: [Agent Requirements](https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html)

Described for only US and Europe.

**Comment by scaleoutsean** [comment]
@kulkarnn there's [APAC too](https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html#cloud-network-access-rules)

**Comment by netapp-alavoie** [comment]
APAC has been added to the CS Requirements page: https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html#cloud-network-access-rules
