### ISSUE TITLE
Missing link to AWS Marketplace for Premium Edition

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/cloudinsights#1519]
![image](https://user-images.githubusercontent.com/16622642/125438018-79edabca-581e-425a-a925-0205176c6096.png)

Page: [Subscribing to Cloud Insights](https://docs.netapp.com/us-en/cloudinsights/concept_subscribing_to_cloud_insights.html)

There's just one link to AWS Marketplace, and it's to CI Standard Edition. Once you get to that page, you may not realize there's a different page for Premium Edition, and incorrectly budget for CI, or realize that some features aren't there... 

It would be better if we provided the both AWS subscription pages, both Standard and Premium:

> "your data via NetApp Sales direct or AWS Marketplace ([Standard](https://github.com/NetAppDocs/cloudinsights/issues/) or [Premium](https://github.com/NetAppDocs/cloudinsights/issues/)).

**Comment by netapp-alavoie** [comment]
Separated links and added one for Premium.
