### ISSUE TITLE
Legal Notices section seems to be missing

### ISSUE THREAD

**Issue by mkniep** [NetAppDocs/cloudinsights#1536]
Most NetApp documentation contains a legal notices regarding what third-party or open-source software was used but I can't seem to find it for Cloud Insights. Could we get a page included like this?

**Comment by netapp-alavoie** [comment]
Hi Miles!

Let me look into this.  

-Tony

**Comment by netapp-alavoie** [comment]
Legal Notices are now present in Cloud Insights documentation.
