### ISSUE TITLE
Cloud Secure - Centos 8 - Firewall configuration

### ISSUE THREAD

**Issue by pixelchrome** [NetAppDocs/cloudinsights#1635]
Page: [Cloud Secure Agent Installation](https://docs.netapp.com/us-en/cloudinsights/task_cs_add_agent.html)

With Centos 8, the documented command `sudo iptables-save | grep 35000` doesn't show any output.

A `firewall-cmd --zone=public --list-ports` will show the ports

```
$ sudo firewall-cmd --zone=public --list-ports
35000-55000/tcp
```

**Comment by netapp-alavoie** [comment]
Added this line.
