### ISSUE TITLE
Kubernetes columns are missing in the Schema Tables

### ISSUE THREAD

**Issue by drosinsk** [NetAppDocs/cloudinsights#1644]
Page: [Cloud Insights Schemas for Reporting](https://docs.netapp.com/us-en/cloudinsights/reference_schemas.html)

**Comment by netapp-alavoie** [comment]
Schema tables are being updated to reflect Kubernetes. Stay tuned in the coming weeks to see these updates.

**Comment by netapp-alavoie** [comment]
This issue is not forgotten.  I am waiting for source files from my appropriate team and these schemas will be published once those are all in place.

**Comment by netapp-alavoie** [comment]
The Schema files now include Kubernetes.
