### ISSUE TITLE
Cloud Insights agent is the Acquisition Unit ?

### ISSUE THREAD

**Issue by pixelchrome** [NetAppDocs/cloudinsights#1652]
Page: [Agent Requirements](https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html)

This note might be confusing

_Please note: **Cloud Insights agent** and Cloud Secure agent can be installed in the same machine._

The **Cloud Insights agent** should be replaced with **Acquisition Unit**

**Comment by netapp-alavoie** [comment]
Separated CI Agent and AU and mentioned both.
