### ISSUE TITLE
please provide detailed information for how to create Client ID

### ISSUE THREAD

**Issue by lewip** [NetAppDocs/cloudinsights#1684]
Hi team,

Page: [NetApp Google Compute data collector](https://docs.netapp.com/us-en/cloudinsights/task_dc_google_cloud.html)

Just like "how to set up Azure Compute and Storage Datacollector", could you please put more information on how to create Client ID.  It would help for a lot of customers.  
I have created an easy how to doco for my CI team.

[How to setup GCP.xlsx](https://github.com/NetAppDocs/cloudinsights/files/7685497/How.to.setup.GCP.xlsx)

Thank you,

**Comment by netapp-alavoie** [comment]
Thank you for your comment, and for the excellent source document.  I will draft up a doc page and run it by my appropriate team for approvals.

**Comment by ntap-bmegan** [comment]
@netapp-alavoie - Please update status or close if work is complete.
