### ISSUE TITLE
More detailed information needed 

### ISSUE THREAD

**Issue by clariceward** [NetAppDocs/cloudinsights#1781]
Page: [Alerts](https://docs.netapp.com/us-en/cloudinsights/cs_alert_data.html)

Customer is not finding this information helpful as it is not detailed enough, the customer would like to know what the following statuses mean:

In Progress

Resolved

Dismissed

**Comment by netapp-alavoie** [comment]
I will add a line or two of description for each of these.

**Comment by netapp-alavoie** [comment]
Updated the doc with a brief line for each status.
