### ISSUE TITLE
Last version of ci_reporting_datrabase_schema.pdf

### ISSUE THREAD

**Issue by Vince-Netapp** [NetAppDocs/cloudinsights#1783]
Page: [Cloud Insights Schemas for Reporting](https://docs.netapp.com/us-en/cloudinsights/reference_schemas.html)

**Comment by Vince-Netapp** [comment]
Last PDF version of ci_reporting_database_schema.pdf is not correct when accessed from https://docs.netapp.com/us-en/cloudinsights/reference_schemas.html. Looks like there is a mistype in the last upload of this document as I found it on the repo but named as ci_reporting_datrabase_schema.pdf (datrabase instead of database). Don't know if we can rename it or just upload it again with the correct name.

**Comment by netapp-alavoie** [comment]
You are indeed correct. The file was mis-named.  
I have re-uploaded the newer .pdf file.  Links within the document do not function, but the table of contents links do navigate to the appropriate sections.
