### ISSUE TITLE
Can I use Cloud Secure with Flex Group configuration on CVO?

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/cloudinsights#1858]
Page: [Configuring the Cloud Volumes ONTAP Data Collector](https://docs.netapp.com/us-en/cloudinsights/task_config_cs_incloud.html)

There is not enough information on whether to support FlexGroup.

**Comment by netapp-alavoie** [comment]
This doc page refers users to the SVM doc page, where we do state that Flexgroup is supported. There is no need to add flexgroup mention to this doc page.
