### ISSUE TITLE
There is not enough description on whether to support FlexGroup when using FSxN + Cloud Secure.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/cloudinsights#1859]
Page: [Amazon FSx for NetApp ONTAP Configuration](https://docs.netapp.com/us-en/cloudinsights/task_config_cs_amazon_fsx.html)

I want to know as soon as possible, so please answer.
If this is NG, Cloud Secure will not be used.

**Comment by netapp-alavoie** [comment]
I'm told that Flexgroups have not been tested in FSx, but that it should work. It sounds like there may be a customer need for some sort of official support statement. If this is the case, let me know and I'll pass along that request.

**Comment by netapp-alavoie** [comment]
Closing based on info above.
