### ISSUE TITLE
Wrong link from cloud secure manual page to this link

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/cloudinsights#1860]
Page: [Configuring the ONTAP SVM Data Collector](https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html)

When I click on the Cloud Secure data collector link, I'm taken to the **Cloud Insights** data collector description page.
The link destination seems to be wrong. Please see the image I attached.

Click on 
"Cloud Secure" -> "Getting Started" -> "Configuring the ONTAP SVM Data Collector" 
Then I'm directed to the Cloud Insights manual instead of the Cloud Secure manual.

Cloud Secure should not support FlexGroup, but if this manual link is correct, it will support FlexGroup.
I want to know the correct information as soon as possible.

**Comment by kanitani** [comment]
![image](https://user-images.githubusercontent.com/68621663/167759235-76f1d3cd-7133-4a48-8810-f8f642d51c10.png)

**Comment by netapp-alavoie** [comment]
Closing based on info above.

**Comment by kanitani** [comment]
> Hi Kan!
> 
> I'm not sure what you mean. Cloud Insights documentation includes Cloud Secure, so it's all one manual. The documentation path "Cloud Secure" -> "Getting Started" -> "Configuring the ONTAP SVM Data Collector" correctly takes you to the SVM page you see above. Any links from the Cloud Secure product to documentation will take you to Cloud Insights documentation.
> 
> I'll ask about Flexgroup support.
> 
> -Tony

Cloud Secure does not support FlexGroup. So the description I pointed out is wong.
Please see the screen capture I posted.

**Comment by kanitani** [comment]
OK. I understand.
