### ISSUE TITLE
/opt/netapp needs greater than 30 GB of space

### ISSUE THREAD

**Issue by mhparker44** [NetAppDocs/cloudinsights#1883]
Page: [Agent Requirements](https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html)

docs say Disk space should be allocated in this manner:
/opt/netapp 25-30 GB

If you run the installer with 30GB, you receive an error saying more than 30GB is needed.

Can we please change the docs to say 35GB minimum? or some other number greater than 30? 
I usually recommend this to customers:
/opt/netapp 50GB
/var/log/netapp 50GB

**Comment by netapp-alavoie** [comment]
I am verifying the CS disk requirements before making this change.

**Comment by netapp-alavoie** [comment]
This change has been made in the documentation. Minimum disk space is now stated as 35GB.  Thanks for this feedback!

-Tony
