### ISSUE TITLE
Ubuntu support addition in the documentation

### ISSUE THREAD

**Issue by abhibt** [NetAppDocs/cloudinsights#1910]
Page: [Agent Requirements](https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html)

Supporting Ubuntu version 20 and 22 from 13th July 2022.

**Comment by netapp-alavoie** [comment]
Hello Abhi!

Thanks for your feedback. I will work on adding these versions to the Cloud Secure requirements.

-Tony Lavoie
NetApp Information Engineering (IE) Content Services
