### ISSUE TITLE
Last row for troubleshooting "....(Error Code: AGENT008)”.

### ISSUE THREAD

**Issue by abhibt** [NetAppDocs/cloudinsights#1915]
Page: [Configuring the ONTAP SVM Data Collector](https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html)

The Agent machine may not enough CPU or RAM headroom, that is why the DSCs are failing.
Please check the number of Data Collectors which are added to the Agent in the machine.
If it is more than 20, please increase the CPU and RAM capacity of the Agent machine.
Once the CPU and RAM is increased, the DSCs will get into Initializing and then to Running state automatically.
Look into the sizing guide https://docs.netapp.com/us-en/cloudinsights/concept_cs_event_rate_checker.html in this page.

**Comment by abhibt** [comment]
The above needs to be added into the solution section.

**Comment by netapp-alavoie** [comment]
Hi Abhi!

Thanks for your input.  Are you requesting that the above text be ADDED to the current troubleshooting solution, or should it REPLACE the current solution?
