### ISSUE TITLE
Port 7, should be "Birectional" instead of Outbound.

### ISSUE THREAD

**Issue by abhibt** [NetAppDocs/cloudinsights#1926]
Page: [Agent Requirements](https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html)

Port 7, should be "Birectional" instead of Outbound.

**Comment by netapp-alavoie** [comment]
Hi Abhi!

I'm publishing this correction now.  Thanks for the feedback!

-Tony
