### ISSUE TITLE
There is no description about network access rules

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/cloudinsights#1938]
Page: [Acquisition Unit Requirements](https://docs.netapp.com/us-en/cloudinsights/concept_acquisition_unit_requirements.html)

Please describe network access rules in this requirement section like CS Agent.

CS Agent> https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html#cloud-network-access-rules

If it is same as Cloud Secure Agent, please state so.
And where can I find the access rules for AU? I cannot find it.

**Comment by kanitani** [comment]
I find the description in the other section. 

https://docs.netapp.com/us-en/cloudinsights/task_troubleshooting_linux_acquisition_unit_problems.html
https://docs.netapp.com/us-en/cloudinsights/task_troubleshooting_windows_acquisition_unit_problems.html

```
Considerations about Proxies and Firewalls
If your organization requires proxy usage for internet access, you may need to understand your organization’s proxy behavior and seek certain exceptions for Cloud Insights to work. Keep the following in mind:

First, does your organization block access by default, and only allow access to specific web sites/domains by exception? If so, you will need to get the following domain added to the exception list:

*.cloudinsights.netapp.com
```

It's very inconvenient, so could you please describe these network considerations in this page "https://docs.netapp.com/us-en/cloudinsights/concept_acquisition_unit_requirements.html"?

**Comment by pixelchrome** [comment]
It is described on this page 'Configuring Acquisition Units' -> https://docs.netapp.com/us-en/cloudinsights/task_configure_acquisition_unit.html under 'Proxy Configuration'

For Linux https://docs.netapp.com/us-en/cloudinsights/task_configure_acquisition_unit.html#proxy-configuration
For Windows https://docs.netapp.com/us-en/cloudinsights/task_configure_acquisition_unit.html#proxy-configuration-2

**Comment by kanitani** [comment]
People who don't need to set up a proxy don't read this chapter you pointed to. So isn't it inappropriate to include it in this chapter?
![image](https://user-images.githubusercontent.com/68621663/182270619-e71cc114-ef90-4f17-8d1f-09c719d1da3c.png)

Could you please describe these network considerations on this page "https://docs.netapp.com/us-en/cloudinsights/concept_acquisition_unit_requirements.html"?

**Comment by netapp-alavoie** [comment]
I have added a note about proxies to the requirements page, and in that note I also linked to the expanded proxy/firewall information on the Troubleshooting pages.  Let me know if additional clarification is needed.

Thanks for the feedback, everyone!

**Comment by kanitani** [comment]
OK. Thanks.
