### ISSUE TITLE
Contains unintelligible words.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/cloudinsights#1939]
Page: [Acquisition Unit Requirements](https://docs.netapp.com/us-en/cloudinsights/concept_acquisition_unit_requirements.html)

```
Network
100 Mbps /1 Gbps Ethernet connection, static IP address, IP connectivity to all FC devices, and a required port to the Cloud Insights instance (80 or 443).
```

What does "the Cloud Insights instance" mean?
I can not understand.

**Comment by pixelchrome** [comment]
See https://docs.netapp.com/us-en/cloudinsights/task_cloud_insights_onboarding_1.html#sign-in-and-go

_Once your tenant has been created, at any time you can simply log in to the NetApp Cloud Portal and click Go to Cloud Insights. You will be taken directly to your Cloud Insights environment._

_You can also open a browser directly to your Cloud Insights environment URL, for example:_ `https://<environment-name>.c01.cloudinsights.netapp.com/`

But you are right... in the documentation you will find CI _tenant_, CI _instance_ and CI _environment_ which is not very consistent and should be defined somewhere in the documentation.

**Comment by lewip** [comment]
(Suggestion) How about changing the statement to something like below?

100 Mbps /1 Gbps Ethernet connection, static IP address, and port 80 or 443 connectivity from Acquisition Unit to *.cloudinsights.netapp.com or your Cloud Insights environment (<environment-name>.c01.cloudinsights.netapp.com) is required.  For requirements between Acquisition Unit and each Data Collector, please refer to each Data Collector instruction.

**Comment by netapp-alavoie** [comment]
Thank you all for the feedback and the input.

pixelchrome is correct in that we do use the terms "instance", "environment", and "tenant" to refer to a customer's Cloud Insights service.  I will look into addressing this to provide better consistency across documentation pages.

Thank you, lewip, for your suggested wording. 

And thank you all for helping improve Cloud Insights documentation.

-Tony
Cloud Insights Information Engineering

**Comment by kanitani** [comment]
Hi Tony,

Unifying words is important, but that alone will not solve this problem. This page should contain specific network access rules. (because the page title is "Requirement")
As lewip wrote, I would expect it to be specifically described.

Thanks,

**Comment by netapp-alavoie** [comment]
I have updated the network requirements wording using lewip's suggestion. Please let me know if additional clarification is needed.

**Comment by lewip** [comment]
@netapp-alavoie 

Hi Tony, thanks for the prompt action!  
Just a minor fix please(sorry my original statement was incorrect)

(where is the change?)
"your Cloud Insights environment xxx" part.
===

(current)
100 Mbps /1 Gbps Ethernet connection, static IP address, and port 80 or 443 connectivity from Acquisition Unit to *.cloudinsights.netapp.com or your Cloud Insights environment (.c01.cloudinsights.netapp.com) is required. For requirements between Acquisition Unit and each Data Collector, please refer to each Data Collector instruction.

(please fix to)
100 Mbps /1 Gbps Ethernet connection, static IP address, and port 80 or 443 connectivity from Acquisition Unit to *.cloudinsights.netapp.com or your Cloud Insights environment (https://<environment-name>.c01.cloudinsights.netapp.com) is required.  For requirements between Acquisition Unit and each Data Collector, please refer to each Data Collector instruction.

**Comment by netapp-alavoie** [comment]
Hi lewip!

The current wording in the agent requirements section is as follows.  If this wording is good, I will close this ticket.

"100 Mbps/1 Gbps Ethernet connection, static IP address, and port 80 or 443 connectivity from Acquisition Unit to *.cloudinsights.netapp.com or your Cloud Insights environment (i.e. https://<environment_id>.c01.cloudinsights.netapp.com) is required. For requirements between Acquisition Unit and each Data Collector, please refer to instructions for the Data Collector."

**Comment by lewip** [comment]
@netapp-alavoie 

Hi Tony!
Yes - I have checked and confirmed.  Thank you for taking prompt action!  all good to close the call  :)
