### ISSUE TITLE
 Cloud Secure does not work with FlexCache configuration using SMB.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/cloudinsights#1944]
Page: [Configuring the ONTAP SVM Data Collector](https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html)

Could you please state as a limitation that Cloud Secure does not work with FlexCache configuration using SMB?
Fpolicy feature does not support SMB+FlexCache environment, so Cloud Secure will not work.

Please see the FlexCache document. (Starting in ONTAP9.7, Fpolicy is supported only NFS environment.)
https://docs.netapp.com/us-en/ontap/flexcache/supported-unsupported-features-concept.html

**Comment by netapp-alavoie** [comment]
Thanks for the feedback.  I have updated the SMB page "Before you begin" section to include this note:

- SMB protocol version 3.1 and earlier. Note that Cloud Secure does not work with SMB configurations that use Flexcache. Starting with ONTAP 9.7, Fpolicy is supported only in an NFS environment.
