### ISSUE TITLE
"Manually Restore Users for SMB" is a heading

### ISSUE THREAD

**Issue by abhibt** [NetAppDocs/cloudinsights#1954]
Page: [Blocking User Access](https://docs.netapp.com/us-en/cloudinsights/cs_restrict_user_access.html)
"Manually Restore Users for SMB" is a heading for a section.
It needs to be in the same font and size as "Manually Restore IPs for NFS".

**Comment by netapp-alavoie** [comment]
Hi Abhi!  Thanks for the feedback. I have fixed the header and the change will be live shortly.
