### ISSUE TITLE
Cloud Secure and Reporting in 30 Day Trial

### ISSUE THREAD

**Issue by TheFalldog** [NetAppDocs/cloudinsights#1968]
Page: [Subscribing to Cloud Insights](https://docs.netapp.com/us-en/cloudinsights/concept_subscribing_to_cloud_insights.html)

Hello,

It's my understanding from the CI/CS team that the during the 30 day trial customers can request access to a CS trial. If they have over 500 MU being reported they can also request access to the reporting functionality.

The documentation right now for the trail specifically says it's limited to Standard functionality only. Some clarification of this additional functionality would alleviate some customer confusion I've seen.

Thanks!

**Comment by netapp-alavoie** [comment]
Thank you for the suggestion.  Let me ask some people here about how best to handle/clarify this in the documentation.

-Tony
NetApp Information Engineering

**Comment by netapp-alavoie** [comment]
The handling Trials and the features sets included is evolving and will make this question moot. I will leave this ticket open until those changes are finalized.

**Comment by netapp-alavoie** [comment]
We removed the "Trial = Standard" wording in that section, since Trial Edition no longer limits itself to only Standard features.  
If there is additional customer confusion, let us know the specific nature of that confusion.
