### ISSUE TITLE
Please list ONTAP Select as it is supported for Cloud Secure usage

### ISSUE THREAD

**Issue by lewip** [NetAppDocs/cloudinsights#1989]
Page: [Configuring the ONTAP SVM Data Collector](https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html)

ONTAP Select is tested and supported for Cloud Secure.
https://jira.ngage.netapp.com/browse/CFR-599

Please also list ONTAP Select, how to setup DSC
Thank you.

**Comment by netapp-alavoie** [comment]
Hi Lisa!  Thanks for the feedback. I'll forward this request to the Cloud Secure folks.

-Tony

**Comment by netapp-alavoie** [comment]
We've noted that "ONTAP Select is supported" on the page.

Instructions for setting up the collector are already present on the page...was there something specific about ONTAP Select that you feel should be noted in context of setting up the DSC?

**Comment by lewip** [comment]
@netapp-alavoie 
yes I see that now, thank you for your prompt reply and action!
