### ISSUE TITLE
Importing Dashboards from gallery - out of date

### ISSUE THREAD

**Issue by dougdahlberg** [NetAppDocs/cloudinsights#2022]
Page: [Importing from the Dashboard Gallery](https://docs.netapp.com/us-en/cloudinsights/concept_import_from_dashboard_gallery.html)   The documentation on the website seems out of date.  Not sure if the + gallery button exists any more.

**Comment by netapp-alavoie** [comment]
Thank you for your feedback.  

While the page in question is in fact slightly out of date (it refers to "Dashboard > Show All Dashboards" where the correct menu path is "Dashboards > Dashboards"), the "+From Gallery" is still present for Administrator users.

I will add some brief text to clarify this, as well as correct the menu path.

-Tony

**Comment by dougdahlberg** [comment]
that explains it.  I'm not an admin.  thanks for the clarification.

**Comment by netapp-alavoie** [comment]
You're welcome.  I added a note on the page stating that importing from gallery is available for Admin or Account Owner users, which will at least clarify it for the next person running into this. :)

Thanks for helping make Cloud Insights documentation better!

-Tony
Cloud Insights Information Engineering

**Comment by netapp-alavoie** [comment]
I'm partial to it myself. ;)

Thanks for that feedback as well!  :D

-T
