### ISSUE TITLE
Models supported for ontap power dashboard.

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/cloudinsights#2044]
Page: [What’s New with Cloud Insights](https://docs.netapp.com/us-en/cloudinsights/concept_whats_new.html)

It looks like not all the models are supported to show the power consumption. can you please add those details?
Also it would be great if we can  elaborate on ONTAP power metrics, so that readers will know more.

**Comment by netapp-alavoie** [comment]
Thank you for this input.  
It can be difficult to keep documentation up-to-the-minute with regard to supported data collectors.  Let me look into options for this information.

**Comment by sabarig84** [comment]
how long will this take?

**Comment by netapp-alavoie** [comment]
This issue is still open.  I'm pinging my team for advice and guidance. 

Within the product itself, the ONTAP Essentials dashboards display power information for your current environment, if available.

**Comment by netapp-alavoie** [comment]
I have pinged the experts again to see if we can get some additional information around this.

**Comment by netapp-alavoie** [comment]
This information has been added to the ONTAP data collector documentation page.
