### ISSUE TITLE
Issues with CI AU troubleshootings steps

### ISSUE THREAD

**Issue by TheFalldog** [NetAppDocs/cloudinsights#2045]
This is regarding Page: [Troubleshooting Acquisition Unit Problems on Windows](https://docs.netapp.com/us-en/cloudinsights/task_troubleshooting_windows_acquisition_unit_problems.html)

And https://docs.netapp.com/us-en/cloudinsights/task_troubleshooting_linux_acquisition_unit_problems.html

Pertaining to the troubleshooting steps... "traceroute" and "wget" are not valid Windows commands. I guess wget is in PS now but not sure people realize that.

Ping and and curl don't seem to work in general with how we've locked down the CI networking.

Doing a trace will at least help the customer show if the requests are leaving their network, but it doesn't seem like there's a full response back there either.

Please take a look and let me know if you find the same issues.

Thanks!

**Comment by netapp-alavoie** [comment]
Thanks for this feedback.  Sorry I missed seeing this comment come in.
I'll look into options to make these instructions clear and accurate.

**Comment by netapp-alavoie** [comment]
I removed the "traceroute" command. The others are all valid in Windows Powershell.

**Comment by TheFalldog** [comment]
What about the issue with ping and curl?

**Comment by TheFalldog** [comment]
Wouldn't AU to CI behave the same as any ol' system (right he right networking config) to CI? Just testing from my computer without any fancy stuff between me and the interwebs I get zero ping responses back. I think y'all are just blocking ping responses as part of policy. I can hit Google and Amazon, but even netapp.com sends zero responses back. 

For curl, as documented, I get error 28 because it's trying to hit port 80 which is no good. Different responses whether I throw in the full URL (https://CI) or tag port 443.
![curl](https://user-images.githubusercontent.com/94693429/220944383-dd16e2fe-b030-42d7-9f7a-1de797e1bf68.PNG)

**Comment by netapp-alavoie** [comment]
Closing this issue due to age.  Please re-open a new issue if additional changes are needed.
