### ISSUE TITLE
Additional Command required - unzip

### ISSUE THREAD

**Issue by pixelchrome** [NetAppDocs/cloudinsights#2060]
Page: [Agent Requirements](https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html)

I would recommend to add to **Commands** also that `unzip` is required for the installation.

**Comment by netapp-alavoie** [comment]
Hi Harald!  Thanks for the feedback, and for helping to improve Cloud Insights documentation.  
This seems like a low-impact addition, so I will go ahead and implement it.

-T

**Comment by netapp-alavoie** [comment]
This is complete.  

Thanks for the comment!
