### ISSUE TITLE
In-network rules - SSH?

### ISSUE THREAD

**Issue by pixelchrome** [NetAppDocs/cloudinsights#2076]
Page: [Agent Requirements](https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html)

I am missing SSH in the **In-network rules** section. Am I correct?

When you look on the task_add_collector_svm.html#permissions-when-adding-via-cluster-management-ip 

There is this setting required:

`security login create -user-or-group-name csuser -application ssh -authmethod password -role csrole`

**Comment by netapp-alavoie** [comment]
I added the following note to the "In-network" section of the Requirements page:

"Note that when adding _csuser_, that user requires SSH access to the ONTAP management LIF." (With a link to the SVM page noted above.)
