### ISSUE TITLE
Trial Version - add Cloud Secure and Reporting

### ISSUE THREAD

**Issue by pixelchrome** [NetAppDocs/cloudinsights#2077]
Page: [Subscribing to Cloud Insights](https://docs.netapp.com/us-en/cloudinsights/concept_subscribing_to_cloud_insights.html)

During a trial you can request the Reporting (with more than 500 MUs in use) and Cloud Secure feature.

This is somehow misleading -> _All features of CLoud Insights Standard Edition are available during this trial._

**Comment by netapp-alavoie** [comment]
The "All features" line above has been removed, to avoid setting incorrect expectations.
