### ISSUE TITLE
Please include steps for reconfiguring proxy settings 

### ISSUE THREAD

**Issue by bruce-johnson** [NetAppDocs/cloudinsights#2078]
Page: [Configuring Acquisition Units](https://docs.netapp.com/us-en/cloudinsights/task_configure_acquisition_unit.html)

https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Insights/Where_is_the_proxy_information_saved_to_in_the_Cloud_Insights_Acquisition_Unit

**Comment by netapp-alavoie** [comment]
Hello Bruce, thanks for this input.  I'll look into getting this addressed in the doc.

-Tony

**Comment by netapp-alavoie** [comment]
We are currently working on adding SecurityAdmin information to the documentation, but until that is finalized I have added a "more information" link in the Linux and Windows Proxy sections to the KB article.
