### ISSUE TITLE
improve the troubleshooting

### ISSUE THREAD

**Issue by dukebdevil** [NetAppDocs/cloudinsights#2079]
Page: [Dell EMC VMAX and PowerMax Family of Devices data collector](https://docs.netapp.com/us-en/cloudinsights/task_dc_emc_vmax_powermax.html)

first- there is little to zero linux guidance...

today I found out why 'cisys' would only get "no devices found" and the collector would error with "unknown error".

fortunately, there is one KB for "solutions enabler" and it is spot on for cloud insights. 
https://mysupport.netapp.com/site/article?lang=en&page=%2FAdvice_and_Troubleshooting%2FData_Infrastructure_Management%2FOnCommand_Insight%2FEMC_Solutions_Enabler_data_collector_fails_inventory_collection_in_Cloud_Insights,_with_error:_%22unknown_code%22&type=solution

it isn't clear if this change needed to be made on the AU's config (client) or the SE server- where the Symmetrix API daemon is running.  
Answer is just add your name to the local daemon_users and you will be empowered on the REMOTE server!

**Comment by netapp-alavoie** [comment]
Hello, and thanks for your comment.  We will look into adjusting the documentation to account for this.

Thanks for helping to improve Cloud Insights documentation.

-Tony

**Comment by netapp-alavoie** [comment]
The solution from the KB article has been added into the existing Troubleshooting tip.
