### ISSUE TITLE
Text and images are too small to read.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/cloudinsights#2099]
Page: [Integration with ONTAP Autonomous Ransomware Protection](https://docs.netapp.com/us-en/cloudinsights/concept_cs_integration_with_ontap_arp.html)

Text and images are too small to read.
Please change the image to a higher resolution, or change it so that I can see the image in a separate window when I click it.

**Comment by netapp-alavoie** [comment]
Thanks for this feedback. The image in question is hard to read. I will work with the team to find a suitable replacement image.

**Comment by netapp-alavoie** [comment]
I have replaced the image on the page with ones better showing the screen.
