### ISSUE TITLE
We may want to rename this section to something along the lines of Sizing guide for Cloud Secure Agent 

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/cloudinsights#2104]
Page: [SVM Event Rate Checker](https://docs.netapp.com/us-en/cloudinsights/concept_cs_event_rate_checker.html)

**Comment by binder1234** [comment]
We may want to rename the section. I'm not sure that I would immediately associate SVM Event Rate Checker with checking the sizing for the Agent.

**Comment by netapp-alavoie** [comment]
Apologies for not responding to this sooner.  I do see the Jira ticket you logged as well, and I will address this issue through that instead of here.  Closing this ticket in favor of Jira.
