### ISSUE TITLE
CS Agent space requirements

### ISSUE THREAD

**Issue by drichiso** [NetAppDocs/cloudinsights#2129]
25-30 GB for /opt/netapp is too small and sometimes the install fails with not enough space.

Page: [Agent Requirements](https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html)
<html>
<body>

Available disk space | 50-55 GBFor Linux, disk space should be allocated in this manner:/opt/netapp 25-30 GB
/var/log/netapp 25 GB
-- | --

</body>
</html>

**Comment by netapp-alavoie** [comment]
This recommendation has been added to the page, in a note following the main requirements table.
