### ISSUE TITLE
In 'Steps to Install Agent', make it clear this is to be done from the 'Security' menu within CI

### ISSUE THREAD

**Issue by brhoffa** [NetAppDocs/cloudinsights#2131]
Page: [Cloud Secure Agent Installation](https://docs.netapp.com/us-en/cloudinsights/task_cs_add_agent.html)

I'd like to see the docs more explicit that this task needs to be done from within the 'Security' context of the CI UI. Then menu structure (Admin > Data Collectors) is the same in both 'Observability' and 'Security' contexts, and the 'Steps to Install Agent' do not specify which context the user should be in when running the task. We had a customer get very confused when trying to add an agent because they were trying - repeatedly - to do it through the Observability context. Maybe we point that out in the menu structure we document (ie call it Security > Admin > Data Collectors) and / or include a screenshot? Thanks for your consideration.

**Comment by netapp-alavoie** [comment]
This is a good suggestion and I will change the line to:

"Under the Security menu, select Admin > Data Collectors > Agents > +Agent"
