### ISSUE TITLE
please remove an instruction from: How to set up Automatic user access blocking? 

### ISSUE THREAD

**Issue by lewip** [NetAppDocs/cloudinsights#2138]
Page: [Blocking User Access](https://docs.netapp.com/us-en/cloudinsights/cs_restrict_user_access.html)

Under below link,
https://docs.netapp.com/us-en/cloudinsights/cs_restrict_user_access.html#how-to-set-up-automatic-user-access-blocking

There is below instruction
Under “Limit User Access” select what mode of restriction should be applied.

This was procedure of either to set "Read Only"  mode or "Block" mode, and this feature is no longer available, 
hence this line should be removed.

**Comment by netapp-alavoie** [comment]
Hi Lisa!  I have removed the line.  Thanks for this feedback and for helping improve Cloud Insights documentation!

-Tony
