### ISSUE TITLE
Trial version allow premium edition to be used.(except Cognos feature) 

### ISSUE THREAD

**Issue by lewip** [NetAppDocs/cloudinsights#2154]
Page: [Subscribing to Cloud Insights](https://docs.netapp.com/us-en/cloudinsights/concept_subscribing_to_cloud_insights.html)

Below is a little misleading.  Premium features apart from Cognos feature is available for trial version, not standard.
also there is a typo: CLoud Insights > Cloud Insights

Currently:
When you sign up for Cloud Insights and your environment is active, you enter into a free, 30-day trial of Cloud Insights. During this trial you can explore the features that Cloud Insights has to offer, in your own environment. All features of CLoud Insights [Standard Edition](https://docs.netapp.com/us-en/cloudinsights/concept_subscribing_to_cloud_insights.html#editions) are available during this trial.

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/92243422/219985973-e2b31a38-9c02-44eb-856b-dc235f1df41e.png">

**Comment by netapp-alavoie** [comment]
Hi Lisa!  Thanks for this feedback.  I'm going to remove the underlined statement altogether, and leave the specific features available in Trial Edition set unspecified.
