### ISSUE TITLE
User Accounts and Roles -  updating section

### ISSUE THREAD

**Issue by Vince-gecko** [NetAppDocs/cloudinsights#2157]
Page: [User Accounts and Roles](https://docs.netapp.com/us-en/cloudinsights/concept_user_roles.html)

Introduction states "(Note that User and Guest roles are not available in the Security feature set.)"

This is not relevant anymore, when assigning roles to a user, there is 4 roles for the security feature (Workload Security Role) : No Access / Guest / User / Administrator

The note should be removed

**Comment by netapp-alavoie** [comment]
Thanks for this comment.  The line you note has been removed from the paragraph. The table speaks for itself in this context.
