### ISSUE TITLE
link 404s

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/cloudinsights#2160]
The following URL 404s:

https://docs.netapp.com/us-en/cloudinsights/concept_cs_attack_simulator.html

This was reported through IT. Please check your link reports and correct this and any other bad links ASAP.

**Comment by netapp-alavoie** [comment]
I found the problem. There was a typo in the source of the page that snuck in during the recent "Cloud Secure" rename.  I have fixed the typo and the page is re-publishing now.

**Comment by netapp-alavoie** [comment]
The page is live again now.
