### ISSUE TITLE
Pls add Port 22 - SSH to the In-network rules Table

### ISSUE THREAD

**Issue by pixelchrome** [NetAppDocs/cloudinsights#2166]
Page: [Workload Security Agent Requirements](https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html)

It happened to me that the Network Admins just had a look on the table and not notified the remark above. The missing SSH permission prevents CIFS/SMB user blocking.

**Comment by netapp-alavoie** [comment]
Thanks for the comment.  Would the following be accurate for the table in this case?

Protocol | Port | Destination | Direction | Description
SSH | 22 | SVM data LIF IP Addresses | Bidirectional | Required for CIFS/SMB user blocking.

**Comment by pixelchrome** [comment]
IMHO it is the Cluster Management IP Address which is being used for SSH

**Comment by netapp-alavoie** [comment]
I added the following line.  Please re-open this ticket or enter a new one if further adjustment is needed.
  
SSH | 22 | Cluster management| Bidirectional | Needed for CIFS/SMB user blocking.
