### ISSUE TITLE
Cloud Insights Onboarding should be updated to reflect the change to bluexp

### ISSUE THREAD

**Issue by pixelchrome** [NetAppDocs/cloudinsights#2187]
Page: [Cloud Insights Onboarding](https://docs.netapp.com/us-en/cloudinsights/task_cloud_insights_onboarding_1.html)

- cloud.netapp.com is now bluexp.netapp.com ;-)
- Maybe some screenshots will help customers to start the onboarding process.

**Comment by netapp-alavoie** [comment]
Thanks for this comment!

**Comment by netapp-alavoie** [comment]
Adjusted the text on the page to better reflect the change from "NetApp Cloud Central" to "NetApp BlueXP". The relevant link has not changed but clicking it appropriately redirects to the BlueXP Portal.
