### ISSUE TITLE
Insights 'Reclaim ONTAP Cold Storage' doesn't seem to exist

### ISSUE THREAD

**Issue by brhoffa** [NetAppDocs/cloudinsights#2203]
Page: [What’s New with Cloud Insights](https://docs.netapp.com/us-en/cloudinsights/concept_whats_new.html)

The 'Reclaim ONTAP Cold Storage' dashboard doesn't seem to exist under Dashboards > Insights. I suspect the feature may not have made this latest release, so maybe this section of the 'What's new' should be pulled until next month?

**Comment by netapp-alavoie** [comment]
The feature is in full preview now and should therefore be more readily available for customers wanting to preview it.  be aware that the functionality and feature sets may still be subject to change.
