### ISSUE TITLE
Documentation is unclear on cifs support

### ISSUE THREAD

**Issue by zarantha** [NetAppDocs/cloudinsights#2281]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html

### Page title

Configuring the ONTAP SVM Data Collector

### Summary

This line is unclear:
SMB protocol version 3.1 and earlier. Note that Workload Security does not work with SMB configurations that use Flexcache. Starting with ONTAP9.7, Fpolicy is supported only in an NFS environment.

I read that as
 - SMB 3.1 and earlier
 - SMB does not work with flexcache
 - SMB not supported after ONTAP 9.7, it only works with NFS

After discussing with engineering, it was clarified that "only in NFS environment" is relevant only for FlexCache volumes

Can we get that line reworded so it doesn't sound like SMB is not supported after 9.7?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Thanks for this question.  I will confirm the correction and make sure the page is updated accordingly.

-Tony
Cloud Insights

**Comment by netapp-alavoie** [comment]
The following has been added to the page, to clarify:

"In systems using Flexcache, starting with ONTAP 9.7, Fpolicy is supported only in an NFS environment."

**Comment by netapp-alavoie** [comment]
The page now includes this disclaimer:

"Note that Workload Security does not work with SMB configurations that use Flexcache. In systems using Flexcache, starting with ONTAP 9.7, Fpolicy is supported only in an NFS environment."
