### ISSUE TITLE
link does not work

### ISSUE THREAD

**Issue by lewip** [NetAppDocs/cloudinsights#2284]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_dc_amazon_s3_as_storage.html

### Page title

onfiguring the AWS S3 as Storage data collector

### Summary

above link should be re-directed to https://docs.netapp.com/us-en/cloudinsights/task_dc_aws_s3.html
currently displays 404 error

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Hi Lisa!  We likely want to fix the link at the source.  What page contains the bad "https://docs.netapp.com/us-en/cloudinsights/task_dc_amazon_s3_as_storage.html" link?

**Comment by netapp-alavoie** [comment]
Hi @lewip ,
Do you know where is the source site/page containing the bad link above?

**Comment by netapp-alavoie** [comment]
I added a temporary copy of the page at the offending URL, and have requested a product change to fix the link to point to the "real" documentation page.  Both solutions prevent the 404 error.
