### ISSUE TITLE
Zero volumes error is not documented in the troubleshooting section

### ISSUE THREAD

**Issue by yadavider** [NetAppDocs/cloudinsights#2295]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_dc_emc_unisphere_rest.html

### Page title

Configuring the Dell EMC Unisphere REST data collector

### Summary

1. Inventory Recent status: Unexpected data retrieved  -Array reported 0  volume
2. If we check the Netapp troubleshooting error document, there is just one step: make sure your credentials for this device are correct, but this issue is not an authentication failure; it is volume showing 0.
3. Please provide us with related issue solutions or steps that can help to solve the issue. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Hello, and thanks for this question. I will run it past the experts and see if we can find the solution you need.

-Tony
Cloud Insights Information Engineering

**Comment by netapp-alavoie** [comment]
Added a troubleshooting tip with this error, suggesting the user confirm the login is authorized to see all volumes.
