### ISSUE TITLE
are the quotes around the Header correct?

### ISSUE THREAD

**Issue by dukebdevil** [NetAppDocs/cloudinsights#2300]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/API_Overview.html

### Page title

Cloud Insights API

### Summary

I get "NOT_AUTHENTICATED" using the syntax in the example in this document
For example, use the following to retrieve storages assets:
curl https://<tenant_host_name>/rest/v1/assets/storages -H 'X-CloudInsights-ApiKey: <API_Access_Token>'

I am successful when I remove the ' ' from before the X and from the end of my Token.

the command was copied from notepad and is not caused by "smart quotes" 

Can't argue with success!  please test your example.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by dukebdevil** [comment]
ok to disregard.   I see that it can work with quotes.  I copied this from swagger and it worked
curl -X GET "https://hz8340.c02.cloudinsights.netapp.com/rest/v1/assets/annotations" -H  "accept: application/json" -H  "X-CloudInsights-ApiKey: HZ0am3" 

if you want to make a minor change.  there is a whitespace in your example after the :  that causes the curl to fail  
ApiKey: <A...
           ^
need to have the : tight to the token

**Comment by netapp-alavoie** [comment]
Thanks for this feedback, and for following up with the additional information.  I'll get that extraneous space removed.
