### ISSUE TITLE
Need to update the scenario of opening Port 7 bidirectional between ONTAP and Cloud Secure

### ISSUE THREAD

**Issue by attar4u** [NetAppDocs/cloudinsights#2307]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html

### Page title

Configuring the ONTAP SVM Data Collector

### Summary

under this link
https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html#troubleshooting

under Problem section:  Collector reports Error Message: “No local IP address found on the connector that can reach the data interfaces of the SVM”.

Can we add point no 9 as " Need to check port 7 is opened or not". 
As documented in the below article.

https://kb.netapp.com/Cloud/BlueXP/Cloud_Insights/Cloud_Secure_Data_Collector_in_error_No_local_IP_address_found_on_the_connector

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Thanks for this feedback.  I have inserted this as Step 8 in the relevant troubleshooting tip:

8. Verify that port 7 is open.

**Comment by attar4u** [comment]
Thanks Tony.
