### ISSUE TITLE
Steps for searching isActive are incorrect now

### ISSUE THREAD

**Issue by zarantha** [NetAppDocs/cloudinsights#2349]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_identify_inactive_devices.html

### Page title

Identifying inactive devices

### Summary

The steps on the doc page are incorrect.

It should be:
Explore -> New Metric Query
Select Storage from the drop down
Click the gear, select isActive
filter by check or select device

Would be nice to have the steps for deleting inactive devices too (bulk actions -> delete inactive devices)
Then when a collector is deleted, that page could be linked.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Thank you for this feedback, zarantha. We will look into updating these instructions.

**Comment by netapp-alavoie** [comment]
These steps have been updated in the documentation.
