### ISSUE TITLE
Data Retention Table not correct

### ISSUE THREAD

**Issue by pixelchrome** [NetAppDocs/cloudinsights#2351]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/concept_ttl_and_downsampling.html

### Page title

Time-to-live (TTL) and downsampled data

### Summary

The Table is no longer correct

1. there is no longer a standard edition available
2. there data for premium is on 90 days available

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Thanks for this feedback, Harald!  I will make these corrections.

**Comment by netapp-alavoie** [comment]
I've brought the table on the documentation page in line with what the sales page says, and included a link to that page as well.
