### ISSUE TITLE
how many DataCollectors are actually required?

### ISSUE THREAD

**Issue by lewip** [NetAppDocs/cloudinsights#2359]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/concept_cs_event_rate_checker.html

### Page title

SVM Event Rate Checker (Agent Sizing Guide)

### Summary

Here Max number of DataCollector is stated as 50
<img width="1014" alt="image" src="https://github.com/NetAppDocs/cloudinsights/assets/92243422/5e6e466b-c650-4d34-a4d5-ed4b0d893bd6">

but here says 10 DataCollectors.
so which one is right?

<img width="972" alt="image" src="https://github.com/NetAppDocs/cloudinsights/assets/92243422/752f7d8e-c881-4c86-8660-97254469a441">

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Thanks for this feedback, Lisa!  I will get clarification and update the page accordingly.

**Comment by netapp-alavoie** [comment]
We'll clarify by noting in the table which CPU/Memory amount supports 50 collectors, and that 50 is the max supported per agent.

**Comment by netapp-alavoie** [comment]
We added some disclaimer text to the page to note that each agent has a hard maximum of 50 collectors, and to try changing CPU and Memory settings to increase the number of collectors in your environment--up to 50.  

I do not have the CPU/Memory numbers that support 50 collectors at this time.  If I get that math, I will add it to the table.

**Comment by netapp-alavoie** [comment]
Closing this ticket due to age and the addition of the disclaimer text.  If additional changes are needed, please open a new ticket.
