### ISSUE TITLE
Out of date procedures?

### ISSUE THREAD

**Issue by dom123dom** [NetAppDocs/cloudinsights#2375]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_configure_data_collectors.html

### Page title

Configuring Data Collectors

### Summary

The menu items referenced in the steps here don't seem to exist?

e.g. 
1. From the Cloud Insights menu, click Admin > Data Collectors

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Thanks for this feedback.  I have fixed this reference as well as a few others that did not match the current menu scheme.  data collectors are now found under Observability > Collectors.
