### ISSUE TITLE
why does this page exist?

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/cloudinsights#2377]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/TBD.html

### Page title

This topic under construction

### Summary

This file should not exist at all.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
It was a carryover from the early days when we were first populating content.  I have removed the page.
