### ISSUE TITLE
"Manage" is not an option on the left sidebar anymore

### ISSUE THREAD

**Issue by dawnr-netapp** [NetAppDocs/cloudinsights#2414]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_device_resolution_ip.html

### Page title

IP device resolution

### Summary

Looks like it's been replaced with "Enrich"

Adding IP devices manually
https://docs.netapp.com/us-en/cloudinsights/task_device_resolution_ip.html#adding-ip-devices-manually

2. Click Manage > Device resolution

Exporting IP device identification to a .CSV file
https://docs.netapp.com/us-en/cloudinsights/task_device_resolution_ip.html#exporting-ip-device-identification-to-a-csv-file

2. Click Manage > Device resolution

Should probably also check the pages for:
Annotations
Annotation Rules
Applications

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Hi Dawn!

There are a number of pages that need updating around the newer menu layout.  I am working through these and you should start seeing these become more consistent over time.

-Tony

**Comment by netapp-alavoie** [comment]
I believe I have changed most of the old references. Closing this ticket. I will continue to scour the pages as updates are made and will open internal tickets for individual correction.
