### ISSUE TITLE
Please add additional info

### ISSUE THREAD

**Issue by lewip** [NetAppDocs/cloudinsights#2415]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_config_user_dir_connect.html

### Page title

Configuring an Active Directory (AD) User Directory Collector

### Summary

For BindDN, please add Domain Read Only permission is required.

<img width="824" alt="image" src="https://github.com/NetAppDocs/cloudinsights/assets/92243422/6bd27032-22ae-4801-9c42-5421b341c05e">

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Hi Lisa!  Thanks for your suggestion.  I'll add a line to the doc page.

**Comment by netapp-alavoie** [comment]
I added "In addition, Domain Read Only permission is required." to the BindDN row of the table.

**Comment by lewip** [comment]
Thank you Tony! checked and confirmed
