### ISSUE TITLE
please change the requirements for Flexcache

### ISSUE THREAD

**Issue by lewip** [NetAppDocs/cloudinsights#2448]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html

### Page title

Configuring the ONTAP SVM Data Collector

### Summary

Flexcache for SMB is now supported please update the doc accordingly.
Thank you,

SMB protocol version 3.1 and earlier. Note that Workload Security does not work with SMB configurations that use Flexcache. In systems using Flexcache, starting with ONTAP 9.7, Fpolicy is supported only in an NFS environment.
![image](https://github.com/NetAppDocs/cloudinsights/assets/92243422/f2ddb050-ae4d-4785-b2a5-20279f86237f)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
The text has been removed.
