### ISSUE TITLE
Add a link to the security advisory page.

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/cloudinsights#2454]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/security_overview.html

### Page title

Cloud Insights Security

### Summary

Can we add a link to https://security.netapp.com/advisory/ so that customers can check the advisory if they have vulnerability concerns. This may lead to less cases if the customer is able to check on their own without having to reach out to support. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Added this link in a separate section at the bottom of the page.
