### ISSUE TITLE
The acquisition unit page doesn't provide any information on updates or security for the Acquisition Unit

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/cloudinsights#2455]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_configure_acquisition_unit.html

### Page title

Configuring Acquisition Units

### Summary

The documentation for the AU doesn't link back to the https://docs.netapp.com/us-en/cloudinsights/security_overview.html with regards to security concerns nor does it mention that we periodically push out updates to the AU. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Thank you for this feedback. Your input helps us ensure the best user experience possible. 
We will evaluate this request and update the documentation as needed.
-Tony
Cloud Insights Information Engineering

**Comment by netapp-alavoie** [comment]
Added the link near the top of the page: "Read about Cloud Insights security [here]."
