### ISSUE TITLE
The Workload Security Agent page doesn't provide information on updates or security for the agent. 

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/cloudinsights#2456]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_cs_add_agent.html

### Page title

Workload Security Agent Installation

### Summary

The documentation for the agent doesn't link back to the https://docs.netapp.com/us-en/cloudinsights/security_overview.html with regards to security concerns nor does it mention that we periodically push out updates to the agent.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by binder1234** [comment]
There was a case that came in recently were a customer asked about a security concern for the machine hosting the agent and asked about the who was responsible for updating the software.

**Comment by netapp-alavoie** [comment]
Thanks for this feedback and for passing along the question.  I believe linking back to the security page is a fairly low-touch solution to alleviate at least some of the security concerns our customers may have, so I will look into implementing these changes as suggested.

Regarding the question: I believe the customer is asking who is responsible for updating the Workload Security agent, is that correct? 

Cloud Insights makes updates to various features and functionalities frequently, and any of these potentially could be related to the WS agent. It is likely impossible to narrow this down to any set schedule. Was there a specific concern that they want to see if it is addressed?

**Comment by netapp-alavoie** [comment]
Added the link near the top of the page: "You can read about Cloud Insights security [here]."

**Comment by netapp-alavoie** [comment]
Closing this issue.  If concerns around this still exist, we can open a new ticket specifically fo those.
