### ISSUE TITLE
NetApp StorageGRID table error

### ISSUE THREAD

**Issue by metalball101** [NetAppDocs/cloudinsights#2458]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/reference_data_collector_support_matrix.html

### Page title

Cloud Insights Data Collector Support Matrix

### Summary

The data collector matrix under NetApp StorageGRID > performance is a bad cut/paste job.  Recommend cleaning it up in the documentation.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Thank for for this feedback, and for helping us improve Cloud Insights.  
We will take a look and correct the issue. 

-Tony
Cloud Insights Information Engineering

**Comment by netapp-alavoie** [comment]
I have manually fixed the formatting of this section of the matrix page. I believe the data is correct but if anything appears incorrect, plese re-open this ticket or log a new one.

-Tony
