### ISSUE TITLE
Make capacity more specific

### ISSUE THREAD

**Issue by pixelchrome** [NetAppDocs/cloudinsights#2462]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html

### Page title

Workload Security Agent Requirements

### Summary

The required diskspace is defined here differently and should be more specific.

In the first table:

_Available disk space: Disk space should be allocated in this manner:
/opt/netapp 35 GB (minimum)_

The second table describes also free space for a dedicated log partition

_Available disk space: 
50-55 GB
For Linux, disk space should be allocated in this manner:
/opt/netapp 25-30 GB
/var/log/netapp 25 GB_

The difference for /opt/netapp is between 35 GB and 25-30GB.

The second problem is, that Linux admins might define the size of the **partition** exactly like described in the tables. The `cloudsecure-agent-install.sh` checks for 35G  ( `check_disk_space ${OPT_NETAPP_DIR} 35` ) free space in the filesystem. Due to the overhead (filesystem vs partition), the partition might not be large enough. And the install script exits with an error.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by pixelchrome** [comment]
Hi Tony,

the size of 35GB is usually big enough. What I discover some times is that VMware Admins create a Linux VM with a Partition-/ or Disk size of exactly 35GB. If you then add a filesystem (via mkfs) on top of that, you have slightly less capacity available. And then the install script fails.

Best regards,

Harald

**Comment by netapp-alavoie** [comment]
I'm changing the line to:
/opt/netapp 36 GB (minimum 35 GB free space after filesystem creation)

**Comment by netapp-alavoie** [comment]
This change will be published in the next documentation update.
