### ISSUE TITLE
Configure the data collector section has incorrect path to the tile for SVM

### ISSUE THREAD

**Issue by dominicb-netapp** [NetAppDocs/cloudinsights#2466]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html

### Page title

Configuring the ONTAP SVM Data Collector

### Summary

For Workload Security, under the section "Configure the data collector"

This line is incorrect:

  Click **Observability** > Collectors > +Data Collectors

It should be:

  Click **Workload Security** > Collectors > +Data Collectors

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Hi Dominic!  Thanks for this feedback.  I have corrected the instructions on the page.
