### ISSUE TITLE
UPDATE:  AU requirements - OS supported - (Oracle Ent. Linux)

### ISSUE THREAD

**Issue by juankar100** [NetAppDocs/cloudinsights#2473]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/concept_acquisition_unit_requirements.html

### Page title

Acquisition Unit Requirements

### Summary

Update with:
* Oracle Enterprise Linux (64-bit): 7.5 through 7.9, 8.1 through **8.9.**

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juankar100** [comment]
Confirmed with CI ENG that there are already customers running OEL 8.9.

**Comment by netapp-alavoie** [comment]
Hi Juan!  I'm working on confirming the supported versions, and will update the requirements page accordingly.  Thank you for this feedback.
-Tony

**Comment by netapp-alavoie** [comment]
The platforms listed in the requirements are the current officially-supported versions. Documentation updates around supported versions occur as a result of the acquistion/collector team officially adding support. Once they inform me that OEL 8.9 is included in their support verifications, I will add it to the requirements.
