### ISSUE TITLE
Add steps to delete the inactive storage

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/cloudinsights#2475]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_identify_inactive_devices.html

### Page title

Identifying inactive devices

### Summary

Creating this per discussion that came up on ICI-13668. 

1. I was not able to find the page by navigating on the left hand side. This only came up on page search.
2. It is not immediately clear that they can click on the bulk action to delete the inactive storage. We can either add the steps or link to https://kb.netapp.com/Cloud/BlueXP/Cloud_Insights/How_to_delete_inactive_storage_in_Cloud_Insights

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Thanks for this feedback! 
1. This should be part of the menu navigation and we'll make sure to add it there.
2. Steps to remove the inactive devices would he informative in this context, so we will look into adding those or referencing the KB.

**Comment by netapp-alavoie** [comment]
This will be published in the public documentation with the next update. 
1. Page added to left-nav menu
2. Mention selkecting devices and choosing bulk actions to delete.
