### ISSUE TITLE
Brocade REST collector not listed in collector list

### ISSUE THREAD

**Issue by dawnr-netapp** [NetAppDocs/cloudinsights#2481]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/data_collector_list.html

### Page title

Cloud Insights Data Collector List

### Summary

The Brocade collector (Brocade FOS REST Data Collector) is missing from the collector list.

Page that needs linked:
https://docs.netapp.com/us-en/cloudinsights/task_dc_brocade_rest.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Hi Dawn!  Thanks for this feedback. The change you suggested has been made and will be published shortly.

**Comment by dawnr-netapp** [comment]
I think the formatting may have been messed up somehow:

![image](https://github.com/NetAppDocs/cloudinsights/assets/35384954/95339944-6fed-432d-a937-df6e4706a349)
