### ISSUE TITLE
Chage request for "Bind DN"

### ISSUE THREAD

**Issue by lewip** [NetAppDocs/cloudinsights#2484]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_config_user_dir_connect.html

### Page title

Configuring an Active Directory (AD) User Directory Collector

### Summary

Please change from 
In addition, Domain Read Only permission is required.
to
In addition, Domain Read Only permission is required.
Required to be a member of the Security group, "Read-only Domain Controllers"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Thanks for this feedback, Lisa!  I made this change and it will be published soon. 

-Tony
