### ISSUE TITLE
Add RHEL 9.x to Workload Security Agent Requirements

### ISSUE THREAD

**Issue by pixelchrome** [NetAppDocs/cloudinsights#2545]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html

### Page title

Workload Security Agent Requirements

### Summary

Add RHEL 9.x to Workload Security Agent Requirements

pls add 9.x to this line

`Red Hat Enterprise Linux 7.x, 8.x 64-bit, SELinux`

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Hi Harald!  Thanks for this feedback. I rarely have insight into timelines around OS support, but I do know the acquisition and collector teams keep new platform versions always in mind.  Once I have official word that RHEL 9 is supported for WS, I will add it to the Requirements.

**Comment by netapp-alavoie** [comment]
Updated the Agent OS  list to match what's currently in CI.
