### ISSUE TITLE
source contains an incorrectly resolved merge conflic

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/cloudinsights#2582]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_configure_data_collectors.html

### Page title

Configuring Data Collectors

### Summary

![image](https://github.com/NetAppDocs/cloudinsights/assets/56453501/7b6832e6-b599-4fa3-a430-eb761e863786)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Quick fix. Done.

**Comment by netapp-alavoie** [comment]
Fixed and live now.
