### ISSUE TITLE
correct list notation in Inventory table

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/cloudinsights#2583]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_dc_emc_vnx_block.html

### Page title

Dell EMC VNX Block Storage (NaviCLI) data collector

### Summary

Lists should be correctly indented and not look like this:

![image](https://github.com/NetAppDocs/cloudinsights/assets/56453501/125b97a4-c939-4149-aaed-3dd210258dd5)

Current notation: 

```
•	From the Cloud Insights Acquisition Unit:
    -	Open a CMD.
```

Correct notation:

```
* From the Cloud Insights Acquisition Unit:
** Open a CMD.
```

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
I have corrected the asciidoc formatting inside the tables and I believe all is good now.
