### ISSUE TITLE
fix notation in Inventory table (not a dupe)

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/cloudinsights#2584]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_dc_oracle_zfs.html

### Page title

Oracle ZFS Storage Appliance data collector

### Summary

This is a different article with an inventory table, probably the same resolution. 

![image](https://github.com/NetAppDocs/cloudinsights/assets/56453501/2fb3c03a-6473-4ef9-8290-e1138d21dbb4)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
I'm not sure I understand. The steps in question are to possibly solve the error seen on the data collector, so in the context of this troubleshooting tip they seem to make sense.

I did change some formatting and spacing to better show the steps.

**Comment by ntap-bmegan** [comment]
The list notation is incorrect. The list should display with bullet symbols, not dashes:

First, you need an empty line before the list starts. 

Second, it looks like you intend two list levels based on the current source:

```
* Correct the Analytics (statistic) scope for the user ${user} with the read only role:
- From the Configuration -> Users screen, put your mouse over the role and double click to allow editing
-	Select "Analytics" from the Scope drop down menu. A list of the possible properties appears.
-	Click the top most check box and it will select all three properties.
-	Click the Add button on the right side.
-	Click the Apply button at the top right of the pop-up window. The pop-up window will close.
```

If that's the case, then you can't use `-` list leaders because those only work - when they work, which they won't because of the missing blank line - for first-level list entries. 

Third, based on the content, the `-` list leader should be `.` because that looks like it should be a numbered list.

```
Possible Solution:

* Correct the Analytics (statistic) scope for the user ${user} with the read only role:
.. From the Configuration -> Users screen, put your mouse over the role and double click to allow editing
.. Select "Analytics" from the Scope drop down menu. A list of the possible properties appears.
.. Click the top most check box and it will select all three properties.
.. Click the Add button on the right side.
.. Click the Apply button at the top right of the pop-up window. The pop-up window will close.
```

That leaves you with a singleton list entry at the first level, second-level list numbering (alpha), and a lot of wasted cell width. 

A better approach is:

```
Possible Solution:

Correct the Analytics (statistic) scope for the user ${user} with the read only role.

. From the Configuration -> Users screen, put your mouse over the role and double click to allow editing
. Select "Analytics" from the Scope drop down menu. A list of the possible properties appears.
. Click the top most check box and it will select all three properties.
. Click the Add button on the right side.
. Click the Apply button at the top right of the pop-up window. The pop-up window will close.
```

**Comment by netapp-alavoie** [comment]
The "*" and "." bullets don't work in a table, unless I am missing something.  I did re-do the steps and added manual numbers to them, which reads much more cleanly now.

**Comment by ntap-bmegan** [comment]
You need to allow AsciiDoc syntax in the column. See the table syntax article in the internal help site.

**Comment by netapp-alavoie** [comment]
Corrected the asciidoc formatting inside the table here.
