### ISSUE TITLE
fix list notation

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/cloudinsights#2585]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/task_io_density_report_no_root.html

### Page title

Ensuring IO density reports describe only internal data volumes

### Summary

![image](https://github.com/NetAppDocs/cloudinsights/assets/56453501/60aa23a4-1f3a-422e-8d1c-33af4708d610)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Fixed the Step formatting.

**Comment by netapp-alavoie** [comment]
Okay, NOW I fixed the step formatting. :) 
Will go live with next publish.
