### ISSUE TITLE
fix the legal notices

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/cloudinsights#2587]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/legal-notices.html

### Page title

Legal notices

### Summary

![image](https://github.com/user-attachments/assets/2a67e775-cafb-4473-a63e-30734c3fa1ae)

Compare to https://docs.netapp.com/us-en/bluexp-setup-admin/legal-notices.html:

![image](https://github.com/user-attachments/assets/d19b037b-2e92-4887-a21b-8cffd02d06e3)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Removed the duplicate lines.

**Comment by netapp-alavoie** [comment]
I believe this is fixed now.
