### ISSUE TITLE
Clarity on Editions 

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/cloudinsights#2637]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/concept_requesting_support.html

### Page title

Requesting Support

### Summary

Under "Obtaining Support Information" section i see that "For users who are subscribed to any of the Data Infrastructure Insights Editions (**Basic*, Standard, Premium**), technical support is available via phone or web ticketing. A NetApp Support Site (NSS) SSO account is required for web ticket along with case management." -> but when i check the pricing page i see only basic and premium. i dont see standard. https://www.netapp.com/cloud-services/cloud-insights/editions-pricing/. Also i would like the docs to clarify what edition customers will get if they buy the new version of support edge advisor.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by sabarig84** [comment]
can i have an update on this one please?

**Comment by netapp-alavoie** [comment]
The "Standard Edition" references have been removed. Please open a new ticket if you discover any others.
Thanks for this feedback, and for helping keep Data Infrastructure Insights documentation up-to-date.
