### ISSUE TITLE
Data Infrastructure Insights API

### ISSUE THREAD

**Issue by juankar100** [NetAppDocs/cloudinsights#2639]
### Page URL

https://docs.netapp.com/us-en/cloudinsights/API_Overview.html

### Page title

Data Infrastructure Insights API

### Summary

Please remove the 'Standard' edition from the table at the beginning. It does not exist anymore. We only provide Basic or Premium. Thank you

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Hi juankar100!  Thanks for this feedback.  The reference to "Standard Edition" has been removed from this page as well as the "Subscribing" page.
