### ISSUE TITLE
Include uninstall instructions for Acquisition Unit

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/cloudinsights#745]
The docs are missing uninstall instructions for the acquisition unit and how to check that it's been uninstalled.

https://docs.netapp.com/us-en/cloudinsights/task_configure_acquisition_unit.html#reinstalling-an-acquisition-unit

**Comment by netapp-alavoie** [comment]
I will add a section for Uninstalling the AU software, and include appropriate Linux/Windows instructions. 

-Tony

**Comment by netapp-alavoie** [comment]
This change is being implemented now.

**Comment by netapp-alavoie** [comment]
Uninstall instructions have been added to the topic.  Please let me know if any additional instructions are needed.
-Tony
