### ISSUE TITLE
Suggestion for security / AU collection updates

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/cloudinsights#750]
Page: [Getting started gathering data](https://docs.netapp.com/us-en/cloudinsights/task_getting_started_with_cloud_insights.html)

Can we add some detail regarding the following - please confirm what is correct etc.
*Where are credentials stored?*
* Credentials are stored on the AU and not passed to the Cloud Insights Tenant, they are intended to stay where the devices are located.

*Are credentials for the devices secure?*
* They are encrypted on the AU
* All communication is via https

*is data exposed to the AU or the CI tenant?*
CI does not collect any PII, note on types of data collected.

**Comment by netapp-alavoie** [comment]
I will capture this in a bug so we can better address it.    Thanks Phoebe!

-Tony

**Comment by netapp-alavoie** [comment]
I have drafted some wording for this and hope to have it finalized today.

**Comment by netapp-alavoie** [comment]
I added a note on credentials in the task_configure_data_collectors.html topic. This note was approved by our Acquisition manager. Please re-open this ticket if you feel additional information is needed.
