### ISSUE TITLE
We should remove the Cloud Secure ICON in this page

### ISSUE THREAD

**Issue by knieberg** [NetAppDocs/cloudinsights#967]
Page: [Switching to other Cloud Central products](https://docs.netapp.com/us-en/cloudinsights/concept_other_cloud_products.html)

Thanks
Kai Niebergall

**Comment by netapp-alavoie** [comment]
Good morning, Kai. Thanks for your comment. 

The Cloud Secure link is still valid, and points to the currently active Cloud Secure [product page](https://cloud.netapp.com/cloud-secure). Can you expand a little on why you think the Cloud Secure icon should be removed from the screen capture on that page at this time?

Thanks!
-Tony

**Comment by knieberg** [comment]
Will do:

Cloud Secure will be a feature of Cloud Insights and no standalone product anymore. Beside the landing page (to gather preview customers) all references which would indicate a standalone product are currently removed.

That is the main reason why I ask you here…  It is just misleading our customers
[cid:image001.png@01D53CB3.CCA8BA40]


Kai Niebergall
Sr Technical Product Manager
Cloud Analytics

**Comment by netapp-alavoie** [comment]
Thanks Kai!

Yes, we will eventually remove CS from that list. Once it is removed from the list in the product, we will update the screenshot to reflect the accurate list. I will talk with product management to make sure this gets tracked with the Cloud Secure integration work being done here so it doesn't fall through the cracks.  

I will leave this issue open in the meantime.

-Tony

**Comment by netapp-alavoie** [comment]
Tracking this as part of Cloud secure story DFPS-3185

**Comment by netapp-alavoie** [comment]
Note sure why this issue was still open. The Screenshot on this page in the CI documentation was updated. It no longer shows Cloud Secure.
