### ISSUE TITLE
Is the JVM documentation the most relevant source document?

### ISSUE THREAD

**Issue by mkniep** [NetAppDocs/cloudinsights#968]
Page: [JVM Data Collector](https://docs.netapp.com/us-en/cloudinsights/task_config_telegraf_jvm.html)

The JVM reference link points to a document from 2013. I suspect there might be something more recent that has additional info.

Current link: https://docs.oracle.com/javase/specs/jvms/se7/html/index.html
Suggested link: https://docs.oracle.com/javase/specs/jvms/se12/html/index.html

**Comment by netapp-alavoie** [comment]
We will update the link to the newer one. Thanks!

**Comment by netapp-alavoie** [comment]
Entered bug for tracking: IBG-16395

**Comment by mkniep** [comment]
I see this is fixed, so closing.
