### ISSUE TITLE
Do we use Telegraf 1.8 as implied in docs, or does the link need to be updated?

### ISSUE THREAD

**Issue by mkniep** [NetAppDocs/cloudinsights#969]
Page: [Configuring an Agent to Collect Data](https://docs.netapp.com/us-en/cloudinsights/task_config_telegraf_agent.html)

The hyperlink on this page for Telegraf points to a version of Telegraf which is stated as no longer under development. If we actually only use this version, I suppose we should leave it - but call out somewhere the Telegraf version used. If not, it should probably point to 1.11 instead.

Possible corrected link: https://docs.influxdata.com/telegraf/v1.11/

**Comment by netapp-alavoie** [comment]
Thanks for the link!  We will update the link in the page to the newer version.

**Comment by netapp-alavoie** [comment]
Tracking in IBG-16396.

**Comment by mkniep** [comment]
Same here, I see it was updated already so closing.
